package com.dcits.smartbip.runtime.impl;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.dcits.smartbip.exception.InvokeException;
import com.dcits.smartbip.runtime.model.ICompositeData;
import com.dcits.smartbip.runtime.model.IService;
import com.dcits.smartbip.runtime.model.impl.AbstractBaseService;
import com.dcits.smartbip.runtime.model.impl.SessionContext;
import com.dcits.smartbip.runtime.model.impl.SoapCompositeData;
import com.dcits.smartbip.utils.CompositeDataUtils;

public class CBSFinanceGeneralCropSignOff extends AbstractBaseService implements IService {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -6441006152372157635L;
	private static final Log log = LogFactory.getLog(CBSFinanceGeneralCropSignOff.class);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public String getId() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
		return "CBSFinanceGeneralCropSignOff";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public String getType() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
		return "base";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public void setType(String type) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public Object execute(Object req) throws InvokeException {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		if (log.isInfoEnabled()) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
			log.info("开始调用基础服务[CBSFinanceGeneralCropSignOff]......");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		// 获得综合签约请求数据对象                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
		ICompositeData Req2002201000104 = (ICompositeData) SessionContext                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
				.getContext().getValue("Req2002201000104");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
		ICompositeData Req3001200000402 = (ICompositeData) SessionContext                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
		.getContext().getValue("Req3001200000402");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
		if (null == Req3001200000402)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			Req3001200000402  = new SoapCompositeData();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
			Req3001200000402.setId("Req3001200000402");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
			Req3001200000402.setxPath("/Req3001200000402");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			getContext().setValue("Req3001200000402",Req3001200000402);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
		List<ICompositeData> signOffArray = CompositeDataUtils.getByPath(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
				Req2002201000104, "ReqAppBody/CBSFinanceGeneralSignOffReq/CBSFinanceGeneralSignOffArray");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
		                             
		String signOffCodeType = (String)SessionContext.getContext().getValue("signCodeType");
		//设置ECIF解约的产品代码
		SessionContext.getContext().setValue("SignProTp",signOffCodeType);
		
		String productNum = initProductNums().get(signOffCodeType);
		
		for (ICompositeData signComposite : signOffArray) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
			String chapdaih = CompositeDataUtils.getValue(signComposite,"chapdaih");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
			if(null != chapdaih && Arrays.asList(productNum.split(",")).contains(chapdaih))
			{
				//核心localhead中需要 加密种子
				CompositeDataUtils.copy(signComposite, Req3001200000402,"shoqguiy", "ReqLocalHead/shoqguiy");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"shoqmima", "ReqLocalHead/shoqmima");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"sqqrenbz", "ReqLocalHead/sqqrenbz");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"syspinsd", "ReqLocalHead/syspinsd");
				
				
//				CompositeDataUtils.copy(signComposite, Req3001200000402,"qsqqczbz", "ReqAppBody/qsqqczbz");
				CompositeDataUtils.setValue(Req3001200000402, "ReqAppBody/qsqqczbz", "4");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"kehuzhao", "ReqAppBody/kehuzhao");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"jiaoymma", "ReqAppBody/jiaoymma");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"zhhuzwmc", "ReqAppBody/zhhuzwmc");
//				CompositeDataUtils.copy(signComposite, Req3001200000402,"chapdaih", "ReqAppBody/chapdaih");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"jujijine", "ReqAppBody/jujijine");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"znckzhlx", "ReqAppBody/znckzhlx");				
				CompositeDataUtils.copy(signComposite, Req3001200000402,"znckzcgz", "ReqAppBody/znckzcgz");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"qyxieyih", "ReqAppBody/qyxieyih");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"zhhaoxuh", "ReqAppBody/zhhaoxuh");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"zhfutojn", "ReqAppBody/zhfutojn");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"kehuleix", "ReqAppBody/kehuleix");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"sfxkkhzh", "ReqAppBody/sfxkkhzh");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"qicunjie", "ReqAppBody/qicunjie");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"huazhyuz", "ReqAppBody/huazhyuz");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"yznkhzbz", "ReqAppBody/yznkhzbz");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"llfdonbz", "ReqAppBody/llfdonbz");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"lilvfdbl", "ReqAppBody/lilvfdbl");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"lcdqclfs", "ReqAppBody/lcdqclfs");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"zdhzbzhi", "ReqAppBody/zdhzbzhi");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"shishbbz", "ReqAppBody/shishbbz");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"sshzjine", "ReqAppBody/sshzjine");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"chufleix", "ReqAppBody/chufleix");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"lchuglfs", "ReqAppBody/lchuglfs");
				CompositeDataUtils.copy(signComposite, Req3001200000402,"mimazlei", "ReqAppBody/mimazlei");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
				                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
				CompositeDataUtils.copy(signComposite, Req3001200000402, "llistinfo", "ReqAppBody/llistinfo");                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
				List<ICompositeData> srcArray1= new ArrayList<ICompositeData>();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
				List<ICompositeData> destArray1= new ArrayList<ICompositeData>();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
				srcArray1 = CompositeDataUtils.getByPath(signComposite, "llistinfo");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
				destArray1 = CompositeDataUtils.getByPath(Req3001200000402, "ReqAppBody/llistinfo");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
				for (int i1 = 0; i1 < srcArray1.size(); i1++) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
					CompositeDataUtils.copy(srcArray1.get(i1), destArray1.get(i1), "cunqiiii", "cunqiiii");                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
					CompositeDataUtils.copy(srcArray1.get(i1), destArray1.get(i1), "baifenbi", "baifenbi");                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
				}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
				                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
			}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
		if (log.isInfoEnabled()) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
			log.info("调用基础服务结束[CBSFinanceGeneralCropSignOff]......");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		return null;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}
	
	private Map<String,String> initProductNums()
	{
		Map<String,String> productNums = new HashMap<String,String>();
		productNums.put("000030", "000030,210012");
		productNums.put("000031", "000031,210013,210014");
		return productNums;
	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

	


