package com.dcits.smartbip.runtime.impl.p2002201000106;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.dcits.smartbip.exception.InvokeException;
import com.dcits.smartbip.runtime.model.ICompositeData;
import com.dcits.smartbip.runtime.model.IService;
import com.dcits.smartbip.runtime.model.impl.AbstractBaseService;
import com.dcits.smartbip.runtime.model.impl.SessionContext;
import com.dcits.smartbip.runtime.model.impl.SoapCompositeData;
import com.dcits.smartbip.utils.CompositeDataUtils;

public class GetsCustAcctList extends AbstractBaseService implements IService {
	
	private static final Log log = LogFactory.getLog(GetsCustAcctList.class);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public String getId() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
		return "GetsCustAcctList";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public String getType() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
		return "base";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public void setType(String type) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public Object execute(Object req) throws InvokeException {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		if (log.isInfoEnabled()) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
			log.info("开始调用基础服务[GetsCustAcctList]......");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		ICompositeData Req2002201000106 = (ICompositeData) SessionContext.getContext().getValue("Req2002201000106");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

		List<ICompositeData> thirdDepMngFlgArray = CompositeDataUtils.getByPath(                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
				Req2002201000106, "ReqAppBody/ThirdDepMngExchgSignReq/ThirdDepMngFlgArray");  
		String sOrganId = "";
		String sCustAcct = "";
		
		List<String> sOrg_sCusList = new ArrayList<String>();
		SessionContext.getContext().setValue("sOrg_sCusList", sOrg_sCusList);
		
		StringBuffer sOrganId_sCustAcct = new StringBuffer();
		for (ICompositeData signOffComposite : thirdDepMngFlgArray) {
			sOrganId = CompositeDataUtils.getValue(signOffComposite,"sOrganId");   
			sCustAcct = CompositeDataUtils.getValue(signOffComposite,"sCustAcct");  
			if(null == sOrganId || null == sCustAcct )
			{
				log.info("sOrganId["+sOrganId+"],sCustAcct[" + sCustAcct + "]为空！");
				continue;
			}else{
				sOrganId_sCustAcct.append(sOrganId).append("_").append(sCustAcct); 
				log.info("三方存款唯一标识[sOrganId_sCustAcct]:"+sOrganId_sCustAcct.toString());
				sOrg_sCusList.add(sOrganId_sCustAcct.toString());
			}		
		}
		
		if (log.isInfoEnabled()) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
			log.info("调用基础服务结束[GetsCustAcctList]......");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		return null;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

	


