package com.dcits.smartbip.runtime.impl;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.dcits.smartbip.exception.InvokeException;
import com.dcits.smartbip.runtime.model.ICompositeData;
import com.dcits.smartbip.runtime.model.IService;
import com.dcits.smartbip.runtime.model.impl.AbstractBaseService;
import com.dcits.smartbip.runtime.model.impl.SessionContext;
import com.dcits.smartbip.runtime.model.impl.SoapCompositeData;
import com.dcits.smartbip.utils.CompositeDataUtils;

public class CBSFinanceGeneralSignResultProcess extends AbstractBaseService implements IService {
	
	private static final Log log = LogFactory.getLog(CBSFinanceGeneralSignResultProcess.class);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public String getId() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
		return "CBSFinanceGeneralSignResultProcess";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public String getType() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
		return "base";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public void setType(String type) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public Object execute(Object req) throws InvokeException {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		if (log.isInfoEnabled()) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
			log.info("开始调用基础服务[CBSFinanceGeneralSignResultProcess]......");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		// 获得综合签约请求数据对象                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
		ICompositeData Rsp2002201000101 = (ICompositeData) SessionContext                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
				.getContext().getValue("Rsp2002201000101"); 
		if (null == Rsp2002201000101)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			Rsp2002201000101  = new SoapCompositeData();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
			Rsp2002201000101.setId("Rsp2002201000101");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
			Rsp2002201000101.setxPath("/Rsp2002201000101");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			getContext().setValue("Rsp2002201000101",Rsp2002201000101);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		}
		
		ICompositeData Rsp3001200000402 = (ICompositeData) SessionContext                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
		.getContext().getValue("Rsp3001200000402");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
		if (null == Rsp3001200000402)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			log.error("返回结果为空!!");
			return null;
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
		String RetCode = CompositeDataUtils.getValue(Rsp3001200000402, "RspSysHead/RetCode");
		if(null != RetCode && ("000000".equalsIgnoreCase(RetCode) || "FnE2004".equalsIgnoreCase(RetCode)))
		{
			log.info("签约成功或已签约！");
			ICompositeData destArrayParent = CompositeDataUtils.mkNodeNotExist(Rsp2002201000101, "RspAppBody/CBSFinanceGeneralSignRes");
			ICompositeData arrayiItem = new SoapCompositeData();
			arrayiItem.setId("CBSFinanceGeneralSignArray");
			destArrayParent.setChild("CBSFinanceGeneralSignArray", arrayiItem);
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/jieszhao", "jieszhao");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/guiylius", "guiylius");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/jioyguiy", "jioyguiy");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/jiaoyirq", "jiaoyirq");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/kehuzhwm", "kehuzhwm");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/yingyjig", "yingyjig");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/qsqqczbz", "qsqqczbz");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/kehuzhao", "kehuzhao");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/kehuzhlx", "kehuzhlx");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/zhhuzwmc", "zhhuzwmc");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/chapbhao", "chapbhao");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/llfdonbz", "llfdonbz");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/lilvfdbl", "lilvfdbl");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/lilvfdsz", "lilvfdsz");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/huazhyuz", "huazhyuz");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/qicunjie", "qicunjie");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/zhfutojn", "zhfutojn");
	       CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/qyxieyih", "qyxieyih");
		   CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/jiaoyije", "jiaoyije");
			
			CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspAppBody/listinfo", "listinfo");
			List<ICompositeData> srcArray1= new ArrayList<ICompositeData>();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
			List<ICompositeData> destArray1= new ArrayList<ICompositeData>();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
			destArray1 = CompositeDataUtils.getByPath(arrayiItem, "llistinfo");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
			srcArray1= CompositeDataUtils.getByPath(Rsp3001200000402, "RspAppBody/llistinfo");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
			for (int i1 = 0; i1 < srcArray1.size(); i1++) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
				CompositeDataUtils.copy(srcArray1.get(i1), destArray1.get(i1), "lckhzhao", "lckhzhao");                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
				CompositeDataUtils.copy(srcArray1.get(i1), destArray1.get(i1), "lczhhxho", "lczhhxho");
				CompositeDataUtils.copy(srcArray1.get(i1), destArray1.get(i1), "licazhao", "licazhao");
				CompositeDataUtils.copy(srcArray1.get(i1), destArray1.get(i1), "cunqiiii", "cunqiiii");
				CompositeDataUtils.copy(srcArray1.get(i1), destArray1.get(i1), "baifenbi", "baifenbi");	
			}
		}
		else
	   {	
			String productId = (String)SessionContext.getContext().getValue("signCodeType");
			String productName = null;
			List serviceIds = (List)SessionContext.getContext().getValue("productList");
			for(Object tmp :serviceIds)
			{
				SignObject signObject = (SignObject)tmp;
				if(signObject.getProductId().equalsIgnoreCase(productId))
				{
					productName = signObject.getProductName();//产品名称
					break;
				}
			}		
			ICompositeData destArrayParent = CompositeDataUtils.mkNodeNotExist(Rsp2002201000101, "RspAppBody");
			ICompositeData arrayiItem = new SoapCompositeData();
			arrayiItem.setId("PrivSignRsltArray");
			destArrayParent.setChild("PrivSignRsltArray", arrayiItem);	
			
			CompositeDataUtils.setValue(arrayiItem, "SignProTp", productId);
			CompositeDataUtils.setValue(arrayiItem, "SignProNm", productName);
			CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspSysHead/RetCode", "RetCode");
			CompositeDataUtils.copy(Rsp3001200000402, arrayiItem, "RspSysHead/RetMsg", "RetMsg");
			CompositeDataUtils.setValue(arrayiItem, "TransStatus", "F");		   
	   }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
		if (log.isInfoEnabled()) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
			log.info("调用基础服务结束[CBSFinanceGeneralSignResultProcess]......");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		return null;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

	


