package com.dcits.smartbip.runtime.impl;
import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.dcits.smartbip.exception.InvokeException;
import com.dcits.smartbip.runtime.model.ICompositeData;
import com.dcits.smartbip.runtime.model.IService;
import com.dcits.smartbip.runtime.model.impl.AbstractBaseService;
import com.dcits.smartbip.runtime.model.impl.SessionContext;
import com.dcits.smartbip.runtime.model.impl.SoapCompositeData;
import com.dcits.smartbip.utils.CompositeDataUtils;

public class DaijiaofeiSignResultProcess extends AbstractBaseService implements IService {
	
	private static final Log log = LogFactory.getLog(DaijiaofeiSignResultProcess.class);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public String getId() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
		return "DaijiaofeiSignResultProcess";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public String getType() {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
		return "base";                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public void setType(String type) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	@Override                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	public Object execute(Object req) throws InvokeException {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		if (log.isInfoEnabled()) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
			log.info("开始调用基础服务[DaijiaofeiSignResultProcess]......");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		// 获得综合签约请求数据对象                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
		ICompositeData Rsp2002201000101 = (ICompositeData) SessionContext                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
				.getContext().getValue("Rsp2002201000101"); 
		if (null == Rsp2002201000101)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			Rsp2002201000101  = new SoapCompositeData();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
			Rsp2002201000101.setId("Rsp2002201000101");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
			Rsp2002201000101.setxPath("/Rsp2002201000101");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			getContext().setValue("Rsp2002201000101",Rsp2002201000101);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		}
		
		ICompositeData Rsp3006200001810 = (ICompositeData) SessionContext                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
		.getContext().getValue("Rsp3006200001810");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
		if (null == Rsp3006200001810)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			log.error("返回结果为空!!");
			return null;
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
		
		/*
		 * 获取原子服务对象
		 */
		String signPro = null;
		String signedRetCode = null;
		try{
			signPro = (String)SessionContext.getContext().getValue("signCodeType");//返回码
			SessionContext.getContext().setValue("SignProTp", signPro);
			List serviceIds = (List)SessionContext.getContext().getValue("productList");
			for(Object tmp :serviceIds)
			{
				SignObject signObject = (SignObject)tmp;
				if(signObject.getProductId().equalsIgnoreCase(signPro))
				{
					signedRetCode = signObject.getSigningRetCode();
					break;
				}
			}		   
		}
		catch(Exception e){
			log.info("签约失败.........." +	"签约产品代码SignProTp="+ signPro);
		}
		
	    String retcode = CompositeDataUtils.getValue(Rsp3006200001810, "RspSysHead/RetCode");
		if("000000".equalsIgnoreCase(retcode) || (null != signedRetCode && signedRetCode.equalsIgnoreCase(retcode)))
		{
			   ICompositeData destArrayParent = CompositeDataUtils.mkNodeNotExist(Rsp2002201000101, "RspAppBody/DirectDebitSignRes");
			   ICompositeData arrayiItem = new SoapCompositeData();
			   arrayiItem.setId("DirectDebitSignArray");
			   destArrayParent.setChild("DirectDebitSignArray", arrayiItem);
			   CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ1/DSYHBH", "FOBJ1/DSYHBH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ1/DISFMC", "FOBJ1/DISFMC");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ1/YWZLBH", "FOBJ1/YWZLBH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ1/DANWBH", "FOBJ1/DANWBH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ1/DSYHDH", "FOBJ1/DSYHDH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ1/ZYWXYH", "FOBJ1/ZYWXYH");
		       
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/ZYWXYH", "FOBJ2/ZYWXYH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/SHMGXX", "FOBJ2/SHMGXX");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/DSYHBH", "FOBJ2/DSYHBH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/DISFMC", "FOBJ2/DISFMC");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/DAILRM", "FOBJ2/DAILRM");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/YWZLBH", "FOBJ2/YWZLBH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/DANWBH", "FOBJ2/DANWBH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/SXIORQ", "FOBJ2/SXIORQ");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/KEHUXM", "FOBJ2/KEHUXM");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/ZHJNZL", "FOBJ2/ZHJNZL");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/ZHJHAO", "FOBJ2/ZHJHAO");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/DSYHDZ", "FOBJ2/DSYHDZ");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/DSYHYB", "FOBJ2/DSYHYB");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/DSYHDH", "FOBJ2/DSYHDH");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/GRZHLX", "FOBJ2/GRZHLX");
		       CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspAppBody/FOBJ2/GRZHAO", "FOBJ2/GRZHAO");	       
		}
		else
		{
			String SignProTp = (String)SessionContext.getContext().getValue("SignProTp");
			log.info("代缴费_"+SignProTp+"签约失败，返回码="+retcode); 
			//向组合服务响应结果中设置错误信息				
			 ICompositeData destArrayParent = CompositeDataUtils.mkNodeNotExist(Rsp2002201000101, "RspAppBody");
			 ICompositeData arrayiItem = new SoapCompositeData();
			 arrayiItem.setId("PrivSignRsltArray");
			 destArrayParent.setChild("PrivSignRsltArray", arrayiItem);
			 CompositeDataUtils.setValue(arrayiItem, "TransStatus", "F");
			 CompositeDataUtils.setValue(arrayiItem, "SignProTp", SignProTp);
			 CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspSysHead/RetCode", "RetCode");
			 CompositeDataUtils.copy(Rsp3006200001810, arrayiItem, "RspSysHead/RetMsg", "RetMsg");
	   }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
		if (log.isInfoEnabled()) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
			log.info("调用基础服务结束[DaijiaofeiSignResultProcess]......");                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
		return null;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
	}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

	


